# Generated by Django 5.1.7 on 2025-04-10 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usertokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokens',
            name='time_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
